#!/usr/bin/env node
//-*- mode:js -*-

'use strict'

// This executable is for development.
// It refers to $/gen indirectly from $/src/runtime.
// So it requires to run `npm run build` to transpile lisp code into JS.

require('./src/runtime/jslisp.js').main()
